import { ArrowUpRight, BriefcaseBusiness, Check, CircleAlert, Clock3 } from "lucide-react";
import type { ActionItem } from "../types";
import { Badge, Card, SectionHeader } from "./ui";

export function Actions({ actions, onConfirm }: { actions: ActionItem[]; onConfirm: (id: string) => Promise<void> }) {
  const open = actions.filter((a) => a.status !== "DONE");
  const done = actions.filter((a) => a.status === "DONE");
  return <div className="page-stack"><div className="page-intro"><div><div className="eyebrow">EXECUTION CONTROL</div><h1>Action queue</h1><p>Every detected coordination issue becomes an accountable next step with an owner, priority, evidence origin and reviewable status.</p></div><div className="intro-stat"><strong>{open.length}</strong><span>open actions</span></div></div><Card><SectionHeader eyebrow="Priority queue" title="What needs an owner now" description="P0 actions are release-critical. P1 actions protect continuity and prevent downstream churn." action={<Badge tone={open.some((a) => a.priority === "P0") ? "critical" : "success"}>{open.filter((a) => a.priority === "P0").length} P0</Badge>} /><div className="action-table">{open.map((action) => <div className="action-card" key={action.id}><div className={`priority-block ${action.priority.toLowerCase()}`}>{action.priority}</div><div className="action-main"><div className="action-title"><strong>{action.title}</strong><Badge tone={action.priority === "P0" ? "critical" : "medium"}>{action.status}</Badge></div><p>{action.reason}</p><div className="action-meta"><span><BriefcaseBusiness size={14}/> {action.owner}</span><span><Clock3 size={14}/> {action.due}</span><span><CircleAlert size={14}/> {action.source_ids.split(",").length} evidence source{action.source_ids.split(",").length > 1 ? "s" : ""}</span></div></div><button className="primary-button" onClick={() => onConfirm(action.id)}><Check size={16}/> Confirm done</button></div>)}</div></Card><Card><SectionHeader eyebrow="Resolved" title="Closed actions" action={<span className="subtle-count">{done.length} completed</span>} /><div className="resolved-list">{done.map((action) => <div className="resolved-row" key={action.id}><Check size={16}/><div><strong>{action.title}</strong><span>{action.owner} · {action.due}</span></div><ArrowUpRight size={15}/></div>)}</div></Card></div>;
}
