import { ArrowRight, GitBranch, ShieldCheck } from "lucide-react";
import type { ProjectState, Signal } from "../types";
import { Badge, Card, SectionHeader } from "./ui";

const kindTone: Record<string, string> = { CHANGE: "change", IMPACT: "impact", BLOCKER: "blocker", APPROVAL: "approval", SUPPLY: "supply", ACTION: "action", OWNER: "owner", DEPENDENCY: "dependency", GATE: "gate" };

export function ImpactGraph({ state, onSignal }: { state: ProjectState; onSignal: (s: Signal) => void }) {
  const columns = distribute(state.graph.nodes, 4);
  const positions = new Map<string, [number, number]>();
  columns.forEach((column, columnIndex) => column.forEach((node, rowIndex) => positions.set(node.id, [120 + columnIndex * 250, 92 + rowIndex * 135])));
  const width = Math.max(1000, columns.length * 250);
  const height = Math.max(480, Math.max(...columns.map((c) => c.length), 1) * 145 + 100);
  return <div className="page-stack"><div className="page-intro"><div><div className="eyebrow">DEPENDENCY INTELLIGENCE</div><h1>See the consequence chain.</h1><p>Relationships are generated from live coordination signals so the graph can grow as new project evidence arrives.</p></div><div className="graph-badge"><GitBranch size={16}/><span>{state.graph.nodes.length} live nodes</span></div></div><Card className="graph-card-large"><SectionHeader eyebrow="Causal map" title="Impact graph" action={<div className="graph-legend"><span><i className="legend-dot change"/>Change</span><span><i className="legend-dot blocker"/>Risk</span><span><i className="legend-dot approval"/>Decision</span><span><i className="legend-dot action"/>Action</span></div>} /><div className="graph-canvas"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Project impact dependency graph"><defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="currentColor" /></marker></defs>{state.graph.edges.map(([from, to]) => { const a = positions.get(from); const b = positions.get(to); if (!a || !b) return null; return <path key={`${from}-${to}`} d={`M ${a[0]} ${a[1]} C ${(a[0] + b[0]) / 2} ${a[1]}, ${(a[0] + b[0]) / 2} ${b[1]}, ${b[0]} ${b[1]}`} className="graph-edge" markerEnd="url(#arrow)"/>; })}{state.graph.nodes.map((node) => { const p = positions.get(node.id)!; const related = state.signals.find((s) => s.title.toLowerCase() === node.label.toLowerCase()); return <g key={node.id} transform={`translate(${p[0]},${p[1]})`} className={related ? "graph-node clickable" : "graph-node"} onClick={() => related && onSignal(related)}><circle r="24" className={`graph-node-circle ${kindTone[node.kind] ?? "dependency"}`}/><rect x="-102" y="35" width="204" height="64" rx="16" className="graph-node-card"/><text x="0" y="56" textAnchor="middle" className="graph-node-kind">{node.kind}</text><text x="0" y="79" textAnchor="middle" className="graph-node-text">{node.label.slice(0, 28)}</text></g>; })}</svg></div></Card><Card><div className="graph-proof"><div className="proof-icon"><ShieldCheck/></div><div><strong>Evidence-backed by design</strong><p>Every signal node can be opened to inspect source messages, reasoning, impact stages and the human decision point. This keeps the “why” visible when a project changes.</p></div><ArrowRight size={18}/></div></Card></div>;
}

function distribute<T>(items: T[], columns: number): T[][] { const result = Array.from({ length: columns }, () => [] as T[]); items.forEach((item, index) => result[index % columns].push(item)); return result.filter((column) => column.length); }
