import { Clock3, FileText, History, MessageSquareText, ShieldCheck } from "lucide-react";
import type { AuditEntry, Message, ProjectState } from "../types";
import { Badge, Card, SectionHeader } from "./ui";

export function Memory({ state }: { state: ProjectState }) {
  return <div className="page-stack"><div className="page-intro"><div><div className="eyebrow">PROJECT MEMORY</div><h1>One source of truth, with evidence.</h1><p>Keep the original project updates, derived coordination signals and human decisions connected so the team can reconstruct why something happened.</p></div></div><div className="grid-2-1"><Card><SectionHeader eyebrow="Inbound context" title="Project activity" description="Messages remain queryable after intelligence is extracted." action={<Badge tone="neutral">{state.messages.length} updates</Badge>} /><div className="memory-timeline">{[...state.messages].reverse().map((message) => <MessageCard message={message} key={message.id}/>)}</div></Card><Card><SectionHeader eyebrow="Auditability" title="Decision trail" action={<History size={18}/>} /><div className="audit-list">{[...state.audit].reverse().slice(0, 18).map((entry) => <AuditItem entry={entry} key={entry.id}/>)}</div></Card></div><Card><SectionHeader eyebrow="Why this matters" title="Evidence-first project memory" /><div className="memory-principles"><div><ShieldCheck/><strong>Source preserved</strong><span>Every captured note keeps its original channel, sender and timestamp.</span></div><div><FileText/><strong>Reasoning traceable</strong><span>Signals point back to their evidence and retain the human decision state.</span></div><div><MessageSquareText/><strong>Coordination recoverable</strong><span>Future teams can understand what changed without reconstructing it manually from chats.</span></div></div></Card></div>;
}

function MessageCard({ message }: { message: Message }) { return <article className="memory-message"><div className="memory-message-top"><div className="channel-icon"><MessageSquareText size={15}/></div><div><strong>{message.sender}</strong><span>{message.channel} · {message.time_label}</span></div><Badge tone="neutral">{message.tag}</Badge></div><p>{message.text}</p></article>; }
function AuditItem({ entry }: { entry: AuditEntry }) { return <div className="audit-item"><div className="audit-line"><div className="audit-icon"><History size={14}/></div><div><strong>{entry.event.replaceAll("_", " ")}</strong><p>{entry.detail}</p><span><Clock3 size={12}/> {new Date(entry.ts).toLocaleString()}</span></div></div></div>; }
