import { ArrowUpRight, Check, CircleAlert, Filter, Search, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import type { ProjectState, Signal } from "../types";
import { Badge, Card, SectionHeader } from "./ui";

const tones: Record<string, string> = { CRITICAL: "critical", HIGH: "high", MEDIUM: "medium", LOW: "neutral" };
const tabs = ["ALL", "CRITICAL", "HIGH", "NEEDS_REVIEW", "CONFIRMED"];

export function Signals({ state, onSignal }: { state: ProjectState; onSignal: (signal: Signal) => void }) {
  const [tab, setTab] = useState("ALL");
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => state.signals.filter((s) => (tab === "ALL" || (tab === "NEEDS_REVIEW" ? s.status === "NEEDS_REVIEW" : tab === s.severity)) && `${s.title} ${s.detail} ${s.owner}`.toLowerCase().includes(query.toLowerCase())), [state.signals, tab, query]);
  return <div className="page-stack"><PageIntro eyebrow="SIGNAL DESK" title="Coordination signals" description="Review evidence-backed changes, blockers, approvals and dependencies before they become expensive downstream surprises." /><Card><div className="toolbar-row"><div className="segmented">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item.replace("_", " ")} <b>{item === "ALL" ? state.signals.length : item === "NEEDS_REVIEW" ? state.signals.filter((s) => s.status === "NEEDS_REVIEW").length : state.signals.filter((s) => s.severity === item).length}</b></button>)}</div><div className="table-search"><Search size={15}/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Filter signals"/><Filter size={15}/></div></div><div className="signal-table">{filtered.map((signal) => <button className="signal-table-row" key={signal.id} onClick={() => onSignal(signal)}><div className={`signal-dot ${tones[signal.severity]}`}><CircleAlert size={16}/></div><div className="signal-main"><div className="signal-heading"><strong>{signal.title}</strong><Badge tone={tones[signal.severity]}>{signal.severity}</Badge><Badge tone="neutral">{signal.type}</Badge></div><p>{signal.detail}</p><span><Sparkles size={13}/> {signal.why}</span></div><div className="signal-owner"><small>OWNER</small><strong>{signal.owner}</strong><span>{signal.confidence}% confidence</span></div><ArrowUpRight size={17}/></button>)}</div></Card></div>;
}

export function SignalDrawer({ signal, state, impact, onClose, onDecision, onRoute, onNotice }: { signal: Signal; state: ProjectState; impact: any; onClose: () => void; onDecision: (id: string, decision: "confirm" | "dismiss") => Promise<void>; onRoute: (id: string, recipient: string, channel: string) => Promise<void>; onNotice: (message: string) => void }) {
  const [routeOpen, setRouteOpen] = useState(false);
  const [recipient, setRecipient] = useState(signal.owner.split("+")[0].trim());
  const [channel, setChannel] = useState("In-app");
  return <div className="drawer-backdrop"><button className="backdrop-close" onClick={onClose} /><aside className="signal-drawer"><div className="drawer-header"><div><div className="eyebrow">SIGNAL · {signal.id}</div><h2>{signal.title}</h2></div><button className="icon-button" onClick={onClose}>×</button></div><div className="drawer-meta"><Badge tone={tones[signal.severity]}>{signal.severity}</Badge><Badge tone="neutral">{signal.type}</Badge><Badge tone={signal.status === "CONFIRMED" ? "success" : signal.status === "DISMISSED" ? "neutral" : "medium"}>{signal.status}</Badge><span className="confidence-pill">{signal.confidence}% evidence</span></div><div className="explain-block"><Sparkles size={17}/><div><strong>Why ThreadPilot surfaced this</strong><p>{signal.why}</p></div></div><div className="owner-block"><div className="avatar large">{signal.owner.slice(0,2).toUpperCase()}</div><div><small>RESPONSIBLE OWNER</small><strong>{signal.owner}</strong><span>{signal.action}</span></div></div><div className="drawer-section"><SectionHeader eyebrow="Impact chain" title="What happens next" />{impact ? <div className="impact-steps">{impact.stages.map((stage: any) => <div className="impact-step" key={stage.step}><div className="step-no">{stage.step}</div><div><small>{stage.label}</small><strong>{stage.value}</strong></div><Badge tone={stage.state === "AT RISK" ? "critical" : stage.state === "ACTION" ? "success" : "neutral"}>{stage.state}</Badge></div>)}</div> : <div className="loading">Loading evidence chain…</div>}</div><div className="drawer-section"><SectionHeader eyebrow="Evidence" title="Source messages" />{(impact?.sources ?? []).map((message: any) => <div className="evidence-card" key={message.id}><div><strong>{message.sender}</strong><span>{message.channel} · {message.time_label}</span></div><p>{message.text}</p></div>)}</div><div className="drawer-footer"><div className="footer-actions">{signal.status !== "CONFIRMED" && <button className="primary-button" onClick={() => onDecision(signal.id, "confirm")}><Check size={16}/> Confirm signal</button>}{signal.status !== "DISMISSED" && signal.status !== "CONFIRMED" && <button className="secondary-button" onClick={() => onDecision(signal.id, "dismiss")}>Dismiss</button>}<button className="secondary-button" onClick={() => setRouteOpen((v) => !v)}><CircleAlert size={16}/> Route alert</button></div>{routeOpen && <div className="route-box"><label>Recipient<select value={recipient} onChange={(e) => setRecipient(e.target.value)}>{state.people.map((p) => <option key={p.id}>{p.name}</option>)}</select></label><label>Channel<select value={channel} onChange={(e) => setChannel(e.target.value)}><option>In-app</option><option>Email</option><option>WhatsApp</option></select></label><button className="primary-button" onClick={async () => { await onRoute(signal.id, recipient, channel); setRouteOpen(false); onNotice(`Coordination alert queued for ${recipient}.`); }}>Queue alert</button></div>}</div></aside></div>;
}

function PageIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="page-intro"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div></div>; }
